# Generated by Django 4.1.4 on 2022-12-20 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_task_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='done',
            new_name='status',
        ),
    ]
