# Generated by Django 4.1.4 on 2022-12-20 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_done_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 7, 25, 47, 564576)),
        ),
    ]
